### ISSUE TITLE
Bug with failing double conversion

### ISSUE THREAD

**Issue by samansmink** [evidence-dev/duckdb_gsheets#34]
First of all, amazing work here @archiewood! Being able to just `SELECT * FROM '<gsheets urls>'` is really amazing! Also the OAuth works super smoothly.

Minor snag I hit:

```
Invalid Error: stod: no conversion
```

for a sheet containing:

col a | col b | col c
-- | -- | --
1 | value1 | blabla1
2 | value2 | blabla2
3 | value3 | blabla3
  | value4 | blabla4

Perhaps it makes sense to look into DuckDB's casting functionality instead of using `stod`? DuckDB has `Value::TryCastAs` which should allow you to do this a bit more safely.

**Comment by archiewood** [comment]
[Reproduced](https://docs.google.com/spreadsheets/d/11QdEasMWbETbFVxry-SsD8jVcdYIT1zBQszcF84MdE8/edit?gid=732080485#gid=732080485)
