### ISSUE TITLE
COPY TO with SQL statements repeats the header rows

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/duckdb_gsheets#40]
If you select rows in the copy statement and union them, then the rows are written one by one, and the header row is duplicated

```sql 
copy (
    select 'Microsoft' as company, 'Excel' as product, 1985 as year_founded
    union all
    select 'Google', 'Google Sheets', 2006
    union all
    select 'Apple', 'Numbers', 1984
    union all
    select 'LibreOffice', 'Calc', 2000) 
to 'https://docs.google.com/spreadsheets/d/11QdEasMWbETbFVxry-SsD8jVcdYIT1zBQszcF84MdE8/edit?gid=1295634987#gid=1295634987' (format gsheet);
```

Result

company | product | year_founded
-- | -- | --
Microsoft | Excel | 1985
company | product | year_founded
Google | Google Sheets | 2006
company | product | year_founded
Apple | Numbers | 1984
company | product | year_founded
LibreOffice | Calc | 2000

**Comment by Alex-Monahan** [comment]
I also see the header rows duplicated once per vector size (every 2048 rows). I wonder if that could be the same issue? Maybe each of these gets its own vector?
