### ISSUE TITLE
Add Test Coverage

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/duckdb_gsheets#7]
- Define SQL tests via the test/ directory (there is an example file already)

- Work out how to pass secrets (e.g tokens) into the test files

- read_sheet()
- COPY TO 'sheet_url'

**Comment by archiewood** [comment]
This will involve to begin with:

1. Defining various things we want to test for each function
2. Creating google sheets with data for read_gsheet tests
3. A test strategy for COPY TO

**Comment by gaatjeniksaan** [comment]
Would it make sense for you to own the test sheets? I could set some up for testing, but probably best if ownership lies with you eventually.

**Comment by gaatjeniksaan** [comment]
Would a nice test strategy for COPY TO be something like:

Read from sheet 1, copy to sheet 2, read from sheet 2 == read from sheet 1

so kinda f(g(x)) = x

**Comment by archiewood** [comment]
I can't really think of a better way off the top of my head.

We will probably need to COPY TO with an empty table at the start of the test to reset the state of the test sheet(s) so that prior runs do not impact future runs

**Comment by archiewood** [comment]
google sheet for testing is: https://docs.google.com/spreadsheets/d/11QdEasMWbETbFVxry-SsD8jVcdYIT1zBQszcF84MdE8

the sheets for reading are all locked to prevent overwrite

use Sheet3 or create new sheets for COPY TO tests

**Comment by gaatjeniksaan** [comment]
Apologies, other projects took my attention away from this one. If there are other testing issues, let me know (or create one here). I'll try to occasionally check in here.

**Comment by archiewood** [comment]
no sweat!
